### ISSUE TITLE
Error (200, SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data): Error creating entry 

### ISSUE THREAD

**Issue by danstowell** [academictorrents/academictorrents-docs#36] opened 2023-01-20 17:26 UTC
Hi. I'm trying to create a new dataset on AcademicTorrents. I fill in all the metadata on https://academictorrents.com/upload.php and submit, and I can't get any further, because I get this error appearing next to the submit button:

`Error (200, SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data): Error creating entry `

Now, I haven't added any JSON, so as the user there's no way for me to diagnose this. I tried taking all the unusual characters out of my metadata, but that didn't fix it. I'm on Firefox 108.0.2 on Ubuntu.

It seems like this must be a programming error since it shouldn't (presumably) be possible to create malformed JSON just by filling in the form. But if it's user error, please do guide me.

![image](https://user-images.githubusercontent.com/202965/213763677-45602771-3425-4106-b9b2-b45ff5810864.png)

**Comment by ieee8023** [comment] 2023-01-20 18:16
Sorry you are experiencing this issue. I added more logging around a part of the code this could be happening. Can you upload the torrent again?

You can leave all the metadata empty and just mark the torrent as "Not Listed" and fill it in later.

You can also email the torrent to contact@academictorrents.com and I can look into it.

**Comment by danstowell** [comment] 2023-01-20 19:19
Thanks for looking into it - I just tried again (reloaded the page, pasted my metadata back in too) -- this time, I got

``Error (400, Bad Request): {"msg","Error creating entry"} ``

**Comment by ieee8023** [comment] 2023-01-20 20:02
Ok I was able to log more that time and I am still confused. Can you send over the torrent file?

**Comment by ieee8023** [comment] 2023-01-20 20:16
Scratch that. I was able to complete the upload of that file and assign it to your account. I think the issue is with how firefox on linux is preparing the request. I will continue to look into it.

**Comment by danstowell** [comment] 2023-01-20 21:19
OK thanks. FYI: I also get the same (original) syntax error when I try to edit the item and add the metadata.

**Comment by ieee8023** [comment] 2023-01-21 00:28
Ok, I figured it out. I found 4 unicode characters (\u00a0) in the abstract that where not being handled correctly. We should have had a better error for that and we will work on it going forward. I edited the entry so all the metadata is there now.

**Closed** 2023-06-03 20:02 UTC
